name: Build and Push Docker Images

on:
  push:

jobs:
  Clearing:
    runs-on: ubuntu-latest
    steps: 
      -
        name: Stop and remove existing container
        uses: actions/checkout@v3
        run: |
          docker ps -q --filter "my_portfolio" | grep -q . && docker stop my_portfolio || echo "No container to stop"
          docker ps -a -q --filter "name=my_portfolio" | grep -q . && docker rm my_portfolio || echo "No container to remove"

  BuildandPush:
    runs-on: ubuntu-latest
    needs:
      - Clearing
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
 #ainer rm -f my_portfolio
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/my_portfolio:latest

  deployment:
    runs-on: ubuntu-latest
    needs: 
      - BuildandPush
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run : |
          echo "${{secrets.PRIVATE_SSH_KEY}}" > key
          chmod 400 key
          
          ssh -o StrictHostKeyChecking=no -i key ${{secrets.USERNAME}}@${{secrets.SERVER_IP}} "docker pull ${{ vars.DOCKERHUB_USERNAME }}/my_portfolio:latest"
          ssh -o StrictHostKeyChecking=no -i key ${{secrets.USERNAME}}@${{secrets.SERVER_IP}} "docker run -d -p 8080:80 --restart=always --name my_portfolio ${{ vars.DOCKERHUB_USERNAME }}/my_portfolio:latest"
          ssh -o StrictHostKeyChecking=no -i key ${{secrets.USERNAME}}@${{secrets.SERVER_IP}} "docker ps"

      - name: Check Container Logs
        run: |
          ssh -o StrictHostKeyChecking=no -i key ${{secrets.USERNAME}}@${{secrets.SERVER_IP}} "docker logs my_portfolio"
